Setup express server
outergamespace/outergamespace pull request #3
Opened 2017-09-28 23:23 UTC by adrianhumphrey111

Simple working express server running on localhost:8080.

2017-09-28 23:26 UTC, lamdbui requested changes
The basic express portion looks fine to me. I'll let @leungleoqin comment on the socket stuff.

Also, on the pull request set the branch to merge into from 'master' to 'develop'

2017-09-28 23:38 UTC, leungleoqin requested changes
We discussed today that we should have two separate routes, '/' for the Game Host (page to be shown on projector), and '/join' for individual Game Players (page to be shown on phone screen). As for the socket communication, I am working on the event names now, but we probably don't need to include those until we start writing the server code.

2017-10-02 04:32 UTC, lamdbui approved these changes

2017-10-02 16:51 UTC, leungleoqin approved these changes

2017-10-02 18:02 UTC, merged